name: jitsi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  jitsi_meet: ^0.2.0
  ddp: ^0.0.13
  crypto: ^2.0.6
  http: ^0.12.0
  json_annotation: ^2.0.0
  audioplayers: ^0.15.1
  intl: ^0.16.1
  dio: ^3.0.9
  file_picker: ^1.4.0+1
  audio_recorder: ^1.0.2
  path_provider: ^1.1.0
  video_player: ^0.10.11+1
  chewie: ^0.9.10
  rxdart: ^0.24.1
  scrollable_positioned_list: ^0.1.7
  scroll_to_index: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  build_runner: ^1.2.7
  json_serializable: ^2.0.2
  permission_handler: ^5.0.1+1
  loadmore: ^1.0.4



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/play_icon.png
    - images/ico_headphone.png
    - images/blue_mic_icon.png
    - images/blue_attachment_icon.png
    - images/blue_camera_icon.png
    - images/members_image.png
